language: ruby

dist: xenial

env:
  - DOCKER_COMPOSE_VERSION=1.23.1
  - DOCKER_COMPOSE_VERSION=1.24.1
  - DOCKER_COMPOSE_VERSION=1.25.4

services:
  - docker

stages:
  - test

before_install:
  - ./script/install-docker-compose.sh
  - docker version
  - docker-compose version
  - docker ps -a

script:
  - ./script/travis.sh

after_script:
  - ./script/cleanup.sh
